(function(d){function n(){this._initMain();this.layerData[this.layers[0].field]=this.layers[0].dataProvider();this._addTab(0);this._hide()}var m=function(a,c){var b=this;b.$element=c;b.options=d.extend({},d.fn.layerselector.defaults,a);d.each(b.options.layers,function(a,c){b.options.layers[a]=d.extend({},d.fn.layerselector.defaultLayer,c)});b.layers=b.options.layers;b.layerCount=b.layers.length;b.columnWidth=Math.floor(b.options.panelWidth/b.options.column)-5;b.layerData={};b.selected={};n.call(b)};
m.prototype={constrcutor:m,_initMain:function(){var a=this;a.$element.textbox({required:a.options.required||!1,editable:!1,icons:[{iconCls:"icon-search",handler:function(){a._show()}}]});a.$element.textbox("textbox").on("click",d.proxy(a._show,a));a.$dialog=d('<div class="panel-body" style="width:'+(a.options.panelWidth+10)+"px;height:"+(a.options.panelHeight+10)+'px;position:relative;z-index:1000111;"><div class="layer-tabs"></div></div>');a.$dialog.appendTo("body");a.$dialog.on("mouseover","ul.tabs>li",
function(){a.$tabs.tabs("select",d(this).index())});a.$dialog.on("mouseover",".link",function(){d(this).addClass("calendar-nav-hover")});a.$dialog.on("mouseout",".link",function(){d(this).removeClass("calendar-nav-hover")});a.$dialog.on("click",".link",function(){var c=d(this),b=d(this).data("id"),h=a.$tabs.tabs("getSelected"),e=a.$tabs.tabs("getTabIndex",h),f=null;b?(d.each(a.layerData[a.layers[e].field],function(c,d){if(d[a.layers[e].idField]===b)return f=d,!0}),a._onSelectLayer(e,f)):0<c.attr("class").indexOf("calendar-selected")?
(f={},f[a.layers[e].idField]=null,a._onSelectLayer(e,f)):a.$element.focus()});a.$dialog.on("click",".ok-button",function(){a._hide()});a.$tabs=a.$dialog.find("div.layer-tabs");a.$tabs.tabs({border:!1,width:a.options.panelWidth+10,height:a.options.panelHeight+10,onUpdate:function(c,b){a.options.multiple&&b==a.layerCount-1&&a.$tabs.tabs("getTab",b).panel("panel").find(".link").each(function(){d(this).removeClass("calendar-selected");var c=d(this).data("id"),e=!1;a.selected[a.layers[b].field]&&(d.each(a.selected[a.layers[b].field],
function(d,g){if(g[a.layers[b].idField]===c)return e=!0}),e?d(this).addClass("calendar-selected"):d(this).removeClass("calendar-selected"))});a.layers[b].otherItem(b?a.selected[a.layers[b-1].field]:null)&&(a.$otherText=d("[name='othertext"+b+"']"),a.$otherText.textbox({buttonText:a.layers[b].otherOkText,onClickButton:function(){var c=a.$otherText.textbox("getText"),d={};d[a.layers[b].labelField]=c;d[a.layers[b].idField]=null;a._onSelectLayer(b,d)}}))}});d("html").on("mousedown",function(c){0===d(c.target).closest(a.$dialog).length&&
a._hide()});a._resetSelectedData()},_show:function(){var a=this.$element.textbox("textbox").offset();this.$dialog.css({top:a.top-7+this.$element.textbox("options").height,left:a.left-9});this.$dialog.css({display:"block"})},_hide:function(){this.$dialog.css({display:"none"})},_addTab:function(a){this.$tabs.tabs("add",{title:this.layers[a].prompt,content:this._generateContent(a),selected:!0})},_generateContent:function(a){for(var c=this.layerData[this.layers[a].field],b=[],d="",e="",f=e=1,g=0;g<c.length;g++){for(f=
1;c[g][this.layers[a].labelField].length*this.options.chracterPixels>this.columnWidth*f&&(f++,e++,f!=this.options.column););e>this.options.column&&(b.push(d),d="",e=f);d+='<div style="width:'+this.columnWidth*f+'px;"><label data-id="'+c[g][this.layers[a].idField]+'" class="link">'+c[g][this.layers[a].labelField]+"</label></div>";0==e%this.options.column?(b.push(d),d="",e=1):e++}d&&b.push(d);c='<div style="width:'+this.options.panelWidth+'px;" class="line"><span style="margin-left:10px;"></span>'+
b.join('</div><div style="width:'+this.options.panelWidth+'px;" class="line"><span style="margin-left:10px;"></span>')+"</div>";this.layers[a].otherItem(0==a?null:this.selected[this.layers[a-1].field])&&(c+='<div style="width:'+this.options.panelWidth+'px;" class="line"><span style="margin-left:10px;"></span><div style="width:'+this.columnWidth+'px;"><label class="link">'+this.layers[a].otherText+'</label></div><div style="width:'+this.columnWidth*(this.options.column-1)+'px;"><input name="othertext'+
a+'" style="width:100%;"></div></div>');return e=this.options.multiple&&a==this.layerCount-1?'<div class="easyui-layout" data-options="fit:true"><div data-options="region:\'center\',border:false">'+c+'</div><div data-options="region:\'south\',border:false" style="height:30px;">'+('<div style="width:'+this.options.panelWidth+'px;text-align:center;vertical-align:middle;"><a href="javascript:void(0)" class="easyui-linkbutton ok-button" data-options="iconCls:\'icon-ok\'" style="width:60px;">'+this.options.okText+
"</a></div></div>")+"</div></div>":'<div class="easyui-layout" data-options="fit:true"><div data-options="region:\'center\',border:false">'+c+"</div></div>"},_resetSelectedData:function(a){for(a=a?a:0;a<this.layers.length;a++)this.selected[this.layers[a].field]=this.options.multiple&&a==this.layerCount-1?[]:null},_resetTabs:function(a){a=a?a:1;for(var c=this.$tabs.tabs("tabs").length-1;c>=a;c--)this.$tabs.tabs("close",c)},_onSelectLayer:function(a,c){var b=this,h=!1,e=b.options.multiple&&a==b.layerCount-
1;if(e){for(var f=b.selected[b.layers[a].field],g=!1,k=0;k<f.length;k++)if(f[k][b.layers[a].idField]===c[b.layers[a].idField]){g=!0;b.selected[b.layers[a].field]=[].concat(f.slice(0,k),f.slice(k+1));break}g||b.selected[b.layers[a].field].push(c)}else b.selected[b.layers[a].field]=c;f=b.$tabs.tabs("getTab",a);g="";f.panel("options").title!=c[b.layers[a].labelField]&&(h=!0);if(e){var l=[];d.each(b.selected[b.layers[a].field],function(c,d){l.push(d[b.layers[a].labelField])});g=l.join(",");g.length*b.options.chracterPixels>
b.options.panelWidth/2&&(g=l[0]+",..,"+l[l.length-1])}else g=c[b.layers[a].labelField];b.$tabs.tabs("update",{tab:f,options:{title:g?g:b.layers[a].prompt}});a==b.layerCount-1?(h=b.options.onSelectData(b.selected),b.$element.textbox("setValue",h),b.options.multiple?null:b._hide()):h?(b.$element.textbox("clear"),b._resetSelectedData(a+1),b._resetTabs(a+1),b.layerData[b.layers[a+1].field]=b.layers[a+1].dataProvider(c),b._addTab(a+1)):b.$tabs.tabs("select",a+1)},load:function(a){this._resetSelectedData();
for(var c=0;c<this.layers.length;c++){for(var b=null,d=a.flag?a.flag:this.layers[c].labelField,e=0;e<this.layerData[this.layers[c].field].length;e++)this.layerData[this.layers[c].field][e][d]===a[this.layers[c].field]&&(b=this.layerData[this.layers[c].field][e]);this._onSelectLayer(c,b)}return this},callMethod:function(a,c){switch(a){case "getText":return this.$element.textbox("getText");case "load":return this.load(c);case "clear":return this._resetSelectedData(),this._resetTabs(),this.$element.textbox("clear"),
this}}};d.fn.layerselector=function(a,c){if("string"===typeof a){var b=d(this).data("layerselector");return b.callMethod(a,c)}return this.each(function(){d(this).data("layerselector",b=new m(a,d(this)))})};d.fn.layerselector.defaults={panelWidth:300,panelHeight:200,column:4,layers:[],multiple:!1,chracterPixels:15,okText:"\u786e  \u5b9a",onSelectData:function(a){var c=this;a=a[c.layers[c.layers.length-1].field];if(c.multiple){var b=[];d.each(a,function(a,d){b.push(d[c.layers[c.layers.length-1].labelField])});
return b.join(",")}return a[c.layers[c.layers.length-1].labelField]}};d.fn.layerselector.defaultLayer={dataProvider:function(a){},idField:"id",labelField:"label",prompt:"Select",otherItem:function(){return!1},otherText:"\u5176\u4ed6",otherOkText:"\u786e\u5b9a"}})(jQuery);
